name: 'Build'

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        commands: |
            git clone https://github.com/ahlstromcj/seq66
            cd seq66
            ./bootstrap --full-clean
            ./bootstrap -er -rm
